export enum NotificationType {
  ORDER_PLACED = 'ORDER_PLACED',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  NEW_MESSAGE = 'NEW_MESSAGE',
  PRICE_DROP = 'PRICE_DROP',
  PRODUCT_AVAILABLE = 'PRODUCT_AVAILABLE',
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
  RESERVATION_CONFIRMED = 'RESERVATION_CONFIRMED',
  NEGOTIATION_RESPONSE = 'NEGOTIATION_RESPONSE',
  SYSTEM = 'SYSTEM'
}
